rails_intro/blog/config/routes.rb
Rails.application.routes.draw do
  get "/articles", to: "articles#index", as: "articles"
  get "/articles/create", to: "articles#new", as: "new_article"
  post "/articles", to: "articles#create"
  get "/articles/:id/edit", to: "articles#edit", as: "edit_article"
  patch "/articles/:id", to: "articles#update"
  delete "/articles/:id", to: "articles#destroy", as: "delete_article"
end

rails_intro/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_intro/blog/app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
end

rails_intro/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

rails_intro/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.all.order(created_at: :asc)
    end

    def new
        @articles = Article.new 
    end

    def create
        @articles = Article.new(article_params)

        if @articles.save
            redirect_to articles_path
        else
            render :new
        end
    end

    def edit
        @articles = Article.find(params[:id])
    end

    def update
        @articles = Article.find(params[:id])

        if @articles.update(article_params)
            redirect_to articles_path
        else
            render :edit
        end

    end

    def destroy
        @articles = Article.find(params[:id]).destroy

        redirect_to articles_path
        
    end

    private

    def article_params
        params.require(:article).permit(:title, :body)
    end
end

rails_intro/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_intro/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

rails_intro/blog/app/views/articles/_form.html.erb
<%= form_with model: @articles do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <% @articles.errors.full_messages_for(:title).each do |message|%>
      <div><%= message %></div>
    <% end %>

  <br/>
    <%= form.label :body %>
  <%= form.text_field :body %>
  <% @articles.errors.full_messages_for(:body).each do |message|%>
      <div><%= message %></div>
    <% end %>

  <br/>
  <%= form.submit "Submit!"%>
<% end %>

rails_intro/blog/app/views/articles/edit.html.erb
<h1> You are editing in ID number <%= @articles.id %> with the title of <%= @articles.title %>!</h1>



<%= form_with model: @articles, url: {action: :update} do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <% @articles.errors.full_messages_for(:title).each do |message|%>
      <div><%= message %></div>
    <% end %>

  <br/>
    <%= form.label :body %>
  <%= form.text_field :body %>
  <% @articles.errors.full_messages_for(:body).each do |message|%>
      <div><%= message %></div>
    <% end %>

  <br/>
  <%= form.submit "Submit!"%>
<% end %>

rails_intro/blog/app/views/articles/index.html.erb
<h1>Show All Articles</h1>

<table>
<tr><th>ID</th>
<th>Title</th>
<th>Body</th>
<th>Actions</th>

</tr>
<% if @articles.length %>
<%@articles.each do |index| %>

<tr>
<td><%= index.id %></td>
<td><%= index.title %></td>
<td><%= index.body %></td>
<td><%= link_to "EDIT", edit_article_path(index.id) %> | <%= link_to "DELETE", delete_article_path(index.id),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></td>

</tr>
<% end %>

<% else %>

<td colspan=3>No Records found!</td>

<% end %>

</table>

<%= link_to "Create New Articles", new_article_path %>

rails_intro/blog/app/views/articles/new.html.erb
<h1>Create a New Article!</h1>

<%= render "form" %>

rails_intro/blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>